# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'binder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # 이미지 로더
  pod 'Kingfisher'
  
  # 파이어베이스
  pod 'Firebase/Firestore'

  # Pods for binder

  target 'binderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'binderUITests' do
    # Pods for testing
  end

end


