# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BINDER' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BINDER
  pod 'FirebaseUI'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'FirebaseUI/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Firestore'
  pod 'FSCalendar'
  pod 'Charts'
  pod 'BulletinBoard'

  # 이미지 로더
  pod 'Kingfisher'
  
  # 파이어베이스
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
end
